apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/owshq-academy/ws-stack-dados-k8s.git'
    path: infra/src/helm-charts/minio-tenant
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'owshq-orion-ws-dev'
      namespace: deepstorage
      server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
